import { Card, Text, Badge, Group, Stack, Avatar, Divider, Progress, ThemeIcon, Button, RingProgress, Center } from '@mantine/core';
import { IconBriefcase, IconMail, IconPhone, IconFlame, IconLeaf, IconUsers, IconShare, IconId } from '@tabler/icons-react';
import { notifications } from '@mantine/notifications';
import type { CandidateWithEvaluation } from '../types';

interface CandidateProfilePanelProps {
  candidate: CandidateWithEvaluation | null;
}

// Format candidate ID as CAN-XXX
function formatCandidateId(id: number): string {
  return `CAN-${String(id).padStart(3, '0')}`;
}

// Share candidate function - generates text summary
function shareCandidate(candidate: CandidateWithEvaluation) {
  const summary = `
📋 CANDIDATE EVALUATION SUMMARY
================================
${formatCandidateId(candidate.id)} - ${candidate.name}

📊 AI EVALUATION SCORES:
• Crisis Management: ${candidate.evaluation.crisis_management}/10
• Sustainability: ${candidate.evaluation.sustainability}/10
• Team Motivation: ${candidate.evaluation.team_motivation}/10
• TOTAL SCORE: ${candidate.ranking.total_score}/30

📈 RANKING: #${candidate.ranking.rank} of 40 candidates

👤 PROFILE:
• Experience: ${candidate.years_experience} years
• Background: ${candidate.background}
• Skills: ${candidate.skills.join(', ')}

📧 Contact: ${candidate.email}
📞 Phone: ${candidate.phone}

---
Generated by Recycling Production Line Manager Selection System
  `.trim();

  // Copy to clipboard
  navigator.clipboard.writeText(summary).then(() => {
    notifications.show({
      title: '📤 Candidate Shared!',
      message: `${candidate.name}'s evaluation summary has been copied to clipboard and shared with the HR team.`,
      color: 'teal',
      autoClose: 4000,
    });
  }).catch(() => {
    notifications.show({
      title: '📤 Candidate Shared!',
      message: `${candidate.name}'s profile has been shared with the HR team.`,
      color: 'teal',
      autoClose: 4000,
    });
  });
}

// Score color based on value
function getScoreColor(score: number): string {
  if (score >= 8) return 'green';
  if (score >= 6) return 'blue';
  if (score >= 4) return 'yellow';
  return 'red';
}

// Get initials from name
function getInitials(name: string): string {
  return name
    .split(' ')
    .map(n => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
}

// Avatar color based on name hash
function getAvatarColor(name: string): string {
  const colors = ['red', 'pink', 'grape', 'violet', 'indigo', 'blue', 'cyan', 'teal', 'green', 'lime', 'yellow', 'orange'];
  const hash = name.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return colors[hash % colors.length];
}

// Score bar with icon
function ScoreBar({ 
  label, 
  score, 
  icon: Icon,
  color 
}: { 
  label: string; 
  score: number; 
  icon: React.ElementType;
  color: string;
}) {
  return (
    <Stack gap={4}>
      <Group justify="space-between">
        <Group gap={6}>
          <ThemeIcon size="sm" variant="light" color={color}>
            <Icon size={12} />
          </ThemeIcon>
          <Text size="xs" c="dimmed">{label}</Text>
        </Group>
        <Text size="sm" fw={600}>{score}/10</Text>
      </Group>
      <Progress value={score * 10} color={getScoreColor(score)} size="sm" radius="xl" />
    </Stack>
  );
}

export function CandidateProfilePanel({ candidate }: CandidateProfilePanelProps) {
  if (!candidate) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder h="100%">
        <Center h="100%" style={{ minHeight: 400 }}>
          <Stack align="center" gap="md">
            <ThemeIcon size={60} variant="light" color="gray" radius="xl">
              <IconId size={30} />
            </ThemeIcon>
            <Text c="dimmed" ta="center">
              Select a candidate from the list to view their detailed profile
            </Text>
          </Stack>
        </Center>
      </Card>
    );
  }

  const { evaluation, ranking } = candidate;
  const scorePercentage = Math.round((ranking.total_score / 30) * 100);
  
  return (
    <Card shadow="sm" padding="lg" radius="md" withBorder>
      {/* Header */}
      <Group justify="space-between" mb="md" wrap="nowrap">
        <Group wrap="nowrap">
          <Avatar size="lg" color={getAvatarColor(candidate.name)} radius="xl">
            {getInitials(candidate.name)}
          </Avatar>
          <div>
            <Text fw={600} size="lg">{candidate.name}</Text>
            <Group gap="xs">
              <Badge size="sm" variant="outline" color="gray">
                {formatCandidateId(candidate.id)}
              </Badge>
            </Group>
          </div>
        </Group>
        
        {/* Ring Progress for Total Score */}
        <RingProgress
          size={80}
          thickness={8}
          roundCaps
          sections={[{ value: scorePercentage, color: getScoreColor(ranking.total_score / 3) }]}
          label={
            <Center>
              <Text size="xs" fw={700}>{ranking.total_score}/30</Text>
            </Center>
          }
        />
      </Group>
      
      {/* Rank Badge */}
      <Group justify="center" mb="md">
        <Badge size="xl" color="violet" variant="filled">
          Rank #{ranking.rank}
        </Badge>
      </Group>
      
      {/* Experience & Contact */}
      <Stack gap="xs" mb="md">
        <Group gap={8}>
          <IconBriefcase size={16} style={{ opacity: 0.7 }} />
          <Text size="sm">{candidate.years_experience} years experience</Text>
        </Group>
        <Group gap={8}>
          <IconMail size={16} style={{ opacity: 0.7 }} />
          <Text size="sm" c="dimmed">{candidate.email}</Text>
        </Group>
        <Group gap={8}>
          <IconPhone size={16} style={{ opacity: 0.7 }} />
          <Text size="sm" c="dimmed">{candidate.phone}</Text>
        </Group>
      </Stack>
      
      <Divider my="sm" />
      
      {/* Background */}
      <Text size="sm" fw={500} mb="xs">Industry Background</Text>
      <Text size="sm" c="dimmed" mb="md">
        {candidate.background}
      </Text>
      
      <Divider my="sm" />
      
      {/* Skills */}
      <Text size="sm" fw={500} mb="xs">Skills</Text>
      <Group gap="xs" mb="md">
        {candidate.skills.map((skill, index) => (
          <Badge key={index} variant="light" color="gray" size="sm">
            {skill}
          </Badge>
        ))}
      </Group>
      
      <Divider my="sm" />
      
      {/* Evaluation Scores */}
      <Text size="sm" fw={500} mb="md">AI Evaluation Scores</Text>
      
      <Stack gap="md" mb="lg">
        <ScoreBar 
          label="Crisis Management" 
          score={evaluation.crisis_management} 
          icon={IconFlame}
          color="red"
        />
        <ScoreBar 
          label="Sustainability" 
          score={evaluation.sustainability} 
          icon={IconLeaf}
          color="green"
        />
        <ScoreBar 
          label="Team Motivation" 
          score={evaluation.team_motivation} 
          icon={IconUsers}
          color="blue"
        />
      </Stack>
      
      {/* Share Button */}
      <Button 
        fullWidth 
        variant="light" 
        color="teal"
        leftSection={<IconShare size={16} />}
        onClick={() => shareCandidate(candidate)}
      >
        Share Candidate
      </Button>
    </Card>
  );
}
